<?php

error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', true);

$code = (isset($_REQUEST['code']))?$_REQUEST['code']:"";
if($code == ""){
	$tipo = (isset($_REQUEST['tipo']))?$_REQUEST['tipo']:"";
	$id = (isset($_REQUEST['id']))?$_REQUEST['id']:"";
}else{
	$code = explode('|',$code);
	$tipo = $code[1];
	$id = $code[0];
}
header("Content-type: text/kml");
header("Content-Disposition: attachment; filename=gps.kml");
header("Pragma: no-cache");
header("Expires: 0");

$html = "";
$html .= '<?xml version="1.0" encoding="UTF-8"?>';
$html .= '<kml xmlns="http://earth.google.com/kml/2.2">';
$html .= '<Document>';
$html .= '<name>Kalitera</name>';
$html .= '<description><![CDATA[Generated by SisManut]]></description>';
$html .= '<Style id="bullet">';
$html .= '<IconStyle>';
$html .= '<Icon>';
$html .= '<href>http://chart.apis.google.com/chart?cht=d&amp;chdp=public&amp;chld=0.18%7C0%7C0000FF%7C15%7Cb%7C00FFFF%7C&amp;chl=%5Bv_disk%270r%5C0r%5C1r%5Cvi%27%5C2r%5CfC%5C%5B6..%27r%5C%5Dha%5CV%5C%5B=%273r%5C%5Dsc%27%5Cf%5C4r%5Cf%5C5r%5CtC%5Cva%5C%5Do%5Cba%5C</href>';
$html .= '</Icon>';
$html .= '</IconStyle>';
$html .= '</Style>';


include('classes/XMLObject.php');
include('classes/database.php');


#Conexão ao banco de dados
$db = Database::getInstance();
switch ($tipo) {
	case "publicidade":
		$query = "";
		$query .= " select codigo_abrigo ||' - '|| endereco ||';'|| gmaps_latitude ||';'|| gmaps_longitude as obs ";
		$query .= " from ocorrencias ";
		$query .= " inner join pontos on pontos.id_ponto = ocorrencias.id_ponto ";
		$query .= " where id_os = " . $id;
		$query .= " and executada = false ";
		$query .= " order by posicao ";
		break;
	case "manutencao":
		$query = "";
		$query .= " select codigo_abrigo ||' - '|| endereco ||';'|| gmaps_latitude ||';'|| gmaps_longitude as obs ";
		$query .= " from ocorrencias ";
		$query .= " inner join pontos on pontos.id_ponto = ocorrencias.id_ponto ";
		$query .= " where id_os = " . $id;
		$query .= " and executada = false ";
		$query .= " order by posicao ";
		break;
	case "vistoria":
		$query = "";
		$query .= " select codigo_abrigo ||' - '|| endereco ||';'|| gmaps_latitude ||';'|| gmaps_longitude as obs ";
		$query .= " from ocorrencias ";
		$query .= " inner join pontos on pontos.id_ponto = ocorrencias.id_ponto ";
		$query .= " where id_vistoria = " . $id;
		$query .= " and executada = false ";
		$query .= " order by posicao ";
		break;
	case "auditoria":
		$query = "select 'Simak:' ||replace(replace(replace(replace(replace(obs,'Latitude:',''),'Simak:',''),'Longitude:',''),' ',';'),'.','.') || ';' || data || ';'|| ip_address || ';\n' as obs from auditoria where acao = 4 order by data desc";
		break;
	default:
		//$query = "select 'Simak:' ||replace(replace(replace(replace(replace(obs,'Latitude:',''),'Simak:',''),'Longitude:',''),' ',';'),'.','.') || ';' || data || ';'|| ip_address || ';\n' as obs from auditoria where acao = 4 order by data desc";

		$query = "";
		$query .= " select codigo_abrigo ||' - '|| endereco ||';'|| gmaps_latitude ||';'|| gmaps_longitude as obs ";
		$query .= " from pontos ";
		$query .= " where char_length(gmaps_latitude) > 10 ";
		break;
}
$db->setQuery($query);
$db->execute();
$dados = $db->getResultSet();

foreach ($dados as $row) {
	$posicao = explode(';',$row["obs"]);
	$html .= '<Placemark>';
	$html .= '<name>'. $posicao[0] .'</name>';
	$html .= '<description><![CDATA[]]></description>';
	$html .= '<styleUrl>#bullet</styleUrl>';
	$html .= '<Point>';
	$html .= '<coordinates>'. $posicao[2] .','. $posicao[1] .',0.000000</coordinates>';
	$html .= '</Point>';
	$html .= '</Placemark>';
}
$html .= '</Document>';
$html .= '</kml>';
echo $html;
?>